HTTP_STATUS_FORBIDDEN = 403
HTTP_STATUS_UNAUTHORIZED = 401

QZONE_CODE_OK = 0
QZONE_CODE_UNKNOWN = -1
QZONE_CODE_LOGIN_EXPIRED = -3000
QZONE_CODE_PERMISSION_DENIED = -403
QZONE_CODE_PERMISSION_DENIED_LEGACY = 403

QZONE_INTERNAL_META_KEY = "_meta"
QZONE_INTERNAL_HTTP_STATUS_KEY = "http_status"

QZONE_MSG_EMPTY_RESPONSE = "empty_response"
QZONE_MSG_INVALID_RESPONSE = "invalid_response"
QZONE_MSG_JSON_PARSE_ERROR = "json_parse_error"
QZONE_MSG_NON_OBJECT_RESPONSE = "non_object_response"
QZONE_MSG_PERMISSION_DENIED = "permission_denied"
